/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.lab;

import org.junit.jupiter.api.Test;

class AppIntTest {
    @Test void messageHash() throws InterruptedException {
        Thread.sleep(5000);
    }
}
