/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */
plugins {
    id("com.gradle.enterprise") version "3.8"
}
gradleEnterprise {
    buildScan {
        server = "https://enterprise-training.gradle.com"
        capture {
            isTaskInputFiles = true
        }
    }
}

rootProject.name = "lab"
include("app")

buildCache {
    local {
        removeUnusedEntriesAfterDays = 30
        isEnabled = false
    }
    remote<HttpBuildCache> {
        url = uri("https://enterprise-training.gradle.com/cache/")
        isPush = true
        credentials {
            username = System.getenv("CACHE_USERNAME")
            password = System.getenv("CACHE_PASSWORD")
        }
    }
}
