/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradlelab;

public class App2 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App2().getGreeting());
    }
}
