/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
    id("com.gradle.enterprise") version "3.16.2"
}

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}

rootProject.name = "no_shared"
include("app")
include("app2")
include("app3")
include(":subprojects:sub1")
include(":subprojects:sub2")
include(":subprojects:sub3")
include(":subprojects:sub4")
include(":subprojects:sub5")
include(":subprojects:sub6")
include(":subprojects:sub7")
include(":subprojects:sub8")
include(":subprojects:sub9")
include(":subprojects:sub10")
include(":subprojects:sub11")
include(":subprojects:sub12")
include(":subprojects:sub13")
include(":subprojects:sub14")
include(":subprojects:sub15")
include(":subprojects:sub16")
include(":subprojects:sub17")
include(":subprojects:sub18")
include(":subprojects:sub19")
include(":subprojects:sub20")
include(":subprojects:sub21")
include(":subprojects:sub22")
include(":subprojects:sub23")
include(":subprojects:sub24")
include(":subprojects:sub25")
include(":subprojects:sub26")
include(":subprojects:sub27")
include(":subprojects:sub28")
include(":subprojects:sub29")
include(":subprojects:sub30")
include(":subprojects:sub31")
include(":subprojects:sub32")
include(":subprojects:sub33")
include(":subprojects:sub34")
include(":subprojects:sub35")
include(":subprojects:sub36")
include(":subprojects:sub37")
include(":subprojects:sub38")
include(":subprojects:sub39")
include(":subprojects:sub40")
include(":subprojects:sub41")
include(":subprojects:sub42")
include(":subprojects:sub43")
include(":subprojects:sub44")
include(":subprojects:sub45")
include(":subprojects:sub46")
include(":subprojects:sub47")
include(":subprojects:sub48")
include(":subprojects:sub49")
include(":subprojects:sub50")
