/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.lab;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class App12Test {
    @Test void appHasAGreeting1() throws InterruptedException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        Thread.sleep(300);
    }

    @Test void appHasAGreeting2() throws InterruptedException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        Thread.sleep(300);
    }

    @Test void appHasAGreeting3() throws InterruptedException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        Thread.sleep(300);
    }
}
