/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "node.h"
#include <cassert>
#include <iostream>
#include <memory>
#include <string>

int main() {
    std::string name("Node 1");
    node* t1 = new node(name);
    //std::unique_ptr<node> t1(new node(name));
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
