/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradlelab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class App3Test {
    @Test void appHasAGreeting() {
        App3 classUnderTest = new App3();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
