/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.gradle.lab

//import com.gradle.lab.old.OldMessage

object App {

  def HELLO: Message  = new Message("Hello World!")

  def main(args: Array[String]): Unit = {
    println(greeting())
    println(HELLO.hasWhitespace())
    println(HELLO.getTextHash())
    //println(new OldMessage("hello there").hasWhitespace())
  }

  def greeting(): String = {
    return HELLO.getTextWithTime()
  }
}
