/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */
plugins {
    id("com.gradle.enterprise") version "3.16.2"
}
gradleEnterprise {
    server = "https://dpeuniversity-develocity.gradle.com"
    buildScan {
        publishAlways()
        capture {
            isTaskInputFiles = true
        }
        obfuscation {
            ipAddresses { addresses -> addresses.map { "0.0.0.0" } }
        }
    }
}

rootProject.name = "lab"
include("app")

buildCache {
    local {
        removeUnusedEntriesAfterDays = 30
        isEnabled = true
    }
    remote(gradleEnterprise.buildCache) {
        isEnabled = false
        isPush = true
    }
}
include("model")
